[build]
  base = "client"
  publish = "build"      # not client/build
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://foma-chatbot.onrender.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200