# Правило для перенаправления API-запросов на ваш бэкенд на Render
[[redirects]]
  from = "/api/*"
  to = "https://foma-chatbot.onrender.com/:splat"
  status = 200
  force = true

# Правило для перенаправления всех остальных запросов на index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200