[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://foma-chatbot.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200